name: Compilar iOS (Sin Firma)

on:
  workflow_dispatch: 

jobs:
  build-ios:
    runs-on: macos-latest 

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias
        run: flutter pub get

      - name: Arrancar de raíz las reglas de firma de Apple
        run: |
          sed -i '' '/DevelopmentTeam/d' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' '/ProvisioningStyle/d' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' '/CODE_SIGN_STYLE/d' ios/Runner.xcodeproj/project.pbxproj
          echo "CODE_SIGNING_REQUIRED=NO" >> ios/Flutter/Release.xcconfig
          echo "CODE_SIGNING_ALLOWED=NO" >> ios/Flutter/Release.xcconfig
          echo "CODE_SIGN_IDENTITY=" >> ios/Flutter/Release.xcconfig
          echo "EXPANDED_CODE_SIGN_IDENTITY=" >> ios/Flutter/Release.xcconfig

      - name: Compilar iOS sin firma de Apple
        run: flutter build ios --release --no-codesign

      - name: Empaquetar a formato instalable (.ipa)
        run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r RescueNet.ipa Payload

      - name: Subir el archivo compilado para descargar
        uses: actions/upload-artifact@v4
        with:
          name: RescueNet-iOS-IPA
          path: RescueNet.ipa